### ISSUE TITLE
Don't require Install app permission for using the app

### ISSUE THREAD

**Issue by NatoBoram** [nekomangaorg/Neko#1693]
### Describe your suggested feature

Some users may want to update the app via [Obtainium](https://github.com/ImranR98/Obtainium) or disable auto-updates. Permissions shouldn't be enforced to use the app, but should be requested before usage instead.

### Other details

|                                                Not granted                                                |                                                Granted                                                |
| :-------------------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------: |
| ![not granted](https://github.com/nekomangaorg/Neko/assets/10495562/c47b036c-e228-48ec-b40f-d091c042013f) | ![granted](https://github.com/nekomangaorg/Neko/assets/10495562/24405997-f4e7-4564-8d22-dc0a763a66c7) |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
My problem with removing this from required is 
1.  People will ignore updates
2.  People will download the update then forget to find the APK and install it

**Comment by sturmgewehrz** [comment]
I had a work profile put into place on my personal phone (long story and my rationale behind this is beyond the scope of this post) sometime after first installing neko. Having this work profile prevents me from giving apps permission to install unknown apps via policy, but I was able to continue using and updating neko just fine by manually grabbing the apk for the latest version and installing it with adb from my PC to my phone. The app and the updates worked just fine throughout all of this.

However, with the latest update being an entirely new install of neko, I'm being prompted with the screen shown above since it's my first time launching this new app. This greyed out "Get started" button is single handedly preventing me from using the latest version of neko. I agree with the points made above by nonproto (although you can still ignore updates either way), but having a hard barrier such as this will prevent me and others like myself from using this app entirely.

Maybe a compromise would work best. Something like how you enable developer mode on android, like tapping the greyed "Get started" button X amount of times before you get a warning that lets you continue anyways?

If something isn't implemented to bypass this, I'll have to find another app entirely even though I had been using and updating it just fine, until being confronted by a single greyed out button...

**Comment by nonproto** [comment]
> I had a work profile put into place on my personal phone (long story and my rationale behind this is beyond the scope of this post) sometime after first installing neko. Having this work profile prevents me from giving apps permission to install unknown apps via policy, but I was able to continue using and updating neko just fine by manually grabbing the apk for the latest version and installing it with adb from my PC to my phone. The app and the updates worked just fine throughout all of this.
> 
> However, with the latest update being an entirely new install of neko, I'm being prompted with the screen shown above since it's my first time launching this new app. This greyed out "Get started" button is single handedly preventing me from using the latest version of neko. I agree with the points made above by nonproto (although you can still ignore updates either way), but having a hard barrier such as this will prevent me and others like myself from using this app entirely.
> 
> Maybe a compromise would work best. Something like how you enable developer mode on android, like tapping the greyed "Get started" button X amount of times before you get a warning that lets you continue anyways?
> 
> If something isn't implemented to bypass this, I'll have to find another app entirely even though I had been using and updating it just fine, until being confronted by a single greyed out button...

Thank you for providing a valid use case.
